name: deploy

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v3
      - name: clone theme
        uses: actions/checkout@v3
        with:
          repository: jvanz/pelican-hyde
          path: hyde
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: install pelican
        run: |
          python -m pip install -U pip
          python -m pip install pelican[markdown]
          pelican-themes -i ./hyde --verbose
          pelican-themes -l
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::767398092744:role/gha_update_blog
          role-session-name: gha_deploy_static
          aws-region: "us-east-1"
      - name: publish
        run: |
          make clean
          make publish
          ls -l ./output/
