name: deploy

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::767398092744:role/gha_update_blog
          role-session-name: gha_deploy_static
          aws-region: "us-east-1"
      - name: publish
        run: |
          make clean
          make publish
          make s3_upload
